postgres:
  dbname: postgres
  host: localhost
  port: 5432
  user:
  password:

testdb:
  dbname: testdb
  host: localhost
  port: 5432
  user:
  password:

default:
  dbname: postgres
  host: localhost

fs:
  dbname: fs
  host: localhost
  port: 5432
  user:
  password:
